### ISSUE TITLE
Combination of npm 7, husky@6 and jira-prepare-commit message needs extra config

### ISSUE THREAD

**Issue by the-ult** [bk201-/jira-prepare-commit-msg#320] opened 2021-04-22 16:10 UTC
### Context

With `npm@7` I kept getting errors with Husky@6.
```
node v15.14.0
npm 7.10.0
```

adding: `--yes` fixed it. (on my machine, but somehow it was still broken on my colleagues machine -> same npm version)
`npx --yes --no-install jira-prepare-commit-msg "$1"`
or
`npm_config_yes=true npx --no-install jira-prepare-commit-msg "$1"`

see: https://omrilotan.medium.com/npx-breaking-on-ci-b9f3f61d4676

@see #308

**Comment by bk201-** [comment] 2021-04-26 12:35
Hi @the-ult! I couldn't repro this issue. My steps:
1. `npm i -g npm@7.10.0`
2. `mkdir husky-test`
3. `cd husky-test`
4. `git init`
5. `npm init -y`
6. `git commit -m "Initial commit"`
7. `npm install husky -D`
8. `npm install jira-prepare-commit-msg -D` since I use --no-install flag therefore package will be searched in $PATH and ./node_modules/.bin
9. `npm set-script prepare "husky install"`
10. `npm run prepare`
11. `npx husky add .husky/prepare-commit-msg 'npx --no-install jira-prepare-commit-msg "$1"'`
12. `git checkout -b JIRA-1234-dev`
13. `git commit -a -m "Test"`
![image](https://user-images.githubusercontent.com/6812525/116082683-5d97aa00-a6a4-11eb-8bc9-55472397b2eb.png)
![image](https://user-images.githubusercontent.com/6812525/116082785-799b4b80-a6a4-11eb-9f07-b5ba0b588eb4.png)
![image](https://user-images.githubusercontent.com/6812525/116083124-f0d0df80-a6a4-11eb-9b7f-87f2f7174801.png)

**Comment by the-ult** [comment] 2021-05-02 14:00
Hey @bk201- 

Still trying to reproduce it on multiple machines.
Atm moment it seems to work without problems. 
Will update the issue if I have some more information.

**Comment by bk201-** [comment] 2021-06-07 05:53
Closed as not reproducible, since there are no updates

**Closed by bk201-** 2021-06-07 05:53 UTC
